import 'package:flutter/material.dart';

class ThemeExporter {
  static String generateDartFile(
    ColorScheme lightScheme,
    ColorScheme darkScheme,
  ) {
    final buffer = StringBuffer();

    buffer.writeln("import 'package:flutter/material.dart';");
    buffer.writeln();
    buffer.writeln('/// Generated by Flutter Themeator');
    buffer.writeln('/// https://github.com/epatel/flutter_themeator');
    buffer.writeln();
    buffer.writeln('abstract final class AppColors {');
    buffer.writeln(
      '  static const ColorScheme lightColorScheme = ColorScheme(',
    );
    _writeColorScheme(buffer, lightScheme);
    buffer.writeln('  );');
    buffer.writeln();
    buffer.writeln('  static const ColorScheme darkColorScheme = ColorScheme(');
    _writeColorScheme(buffer, darkScheme);
    buffer.writeln('  );');
    buffer.writeln('}');

    return buffer.toString();
  }

  static void _writeColorScheme(StringBuffer buffer, ColorScheme scheme) {
    buffer.writeln(
      '    brightness: ${scheme.brightness == Brightness.light ? "Brightness.light" : "Brightness.dark"},',
    );
    buffer.writeln('    primary: ${_colorToConst(scheme.primary)},');
    buffer.writeln('    onPrimary: ${_colorToConst(scheme.onPrimary)},');
    buffer.writeln(
      '    primaryContainer: ${_colorToConst(scheme.primaryContainer)},',
    );
    buffer.writeln(
      '    onPrimaryContainer: ${_colorToConst(scheme.onPrimaryContainer)},',
    );
    buffer.writeln('    primaryFixed: ${_colorToConst(scheme.primaryFixed)},');
    buffer.writeln(
      '    primaryFixedDim: ${_colorToConst(scheme.primaryFixedDim)},',
    );
    buffer.writeln(
      '    onPrimaryFixed: ${_colorToConst(scheme.onPrimaryFixed)},',
    );
    buffer.writeln(
      '    onPrimaryFixedVariant: ${_colorToConst(scheme.onPrimaryFixedVariant)},',
    );
    buffer.writeln('    secondary: ${_colorToConst(scheme.secondary)},');
    buffer.writeln('    onSecondary: ${_colorToConst(scheme.onSecondary)},');
    buffer.writeln(
      '    secondaryContainer: ${_colorToConst(scheme.secondaryContainer)},',
    );
    buffer.writeln(
      '    onSecondaryContainer: ${_colorToConst(scheme.onSecondaryContainer)},',
    );
    buffer.writeln(
      '    secondaryFixed: ${_colorToConst(scheme.secondaryFixed)},',
    );
    buffer.writeln(
      '    secondaryFixedDim: ${_colorToConst(scheme.secondaryFixedDim)},',
    );
    buffer.writeln(
      '    onSecondaryFixed: ${_colorToConst(scheme.onSecondaryFixed)},',
    );
    buffer.writeln(
      '    onSecondaryFixedVariant: ${_colorToConst(scheme.onSecondaryFixedVariant)},',
    );
    buffer.writeln('    tertiary: ${_colorToConst(scheme.tertiary)},');
    buffer.writeln('    onTertiary: ${_colorToConst(scheme.onTertiary)},');
    buffer.writeln(
      '    tertiaryContainer: ${_colorToConst(scheme.tertiaryContainer)},',
    );
    buffer.writeln(
      '    onTertiaryContainer: ${_colorToConst(scheme.onTertiaryContainer)},',
    );
    buffer.writeln(
      '    tertiaryFixed: ${_colorToConst(scheme.tertiaryFixed)},',
    );
    buffer.writeln(
      '    tertiaryFixedDim: ${_colorToConst(scheme.tertiaryFixedDim)},',
    );
    buffer.writeln(
      '    onTertiaryFixed: ${_colorToConst(scheme.onTertiaryFixed)},',
    );
    buffer.writeln(
      '    onTertiaryFixedVariant: ${_colorToConst(scheme.onTertiaryFixedVariant)},',
    );
    buffer.writeln('    error: ${_colorToConst(scheme.error)},');
    buffer.writeln('    onError: ${_colorToConst(scheme.onError)},');
    buffer.writeln(
      '    errorContainer: ${_colorToConst(scheme.errorContainer)},',
    );
    buffer.writeln(
      '    onErrorContainer: ${_colorToConst(scheme.onErrorContainer)},',
    );
    buffer.writeln('    surface: ${_colorToConst(scheme.surface)},');
    buffer.writeln('    onSurface: ${_colorToConst(scheme.onSurface)},');
    buffer.writeln('    surfaceDim: ${_colorToConst(scheme.surfaceDim)},');
    buffer.writeln(
      '    surfaceBright: ${_colorToConst(scheme.surfaceBright)},',
    );
    buffer.writeln(
      '    surfaceContainerLowest: ${_colorToConst(scheme.surfaceContainerLowest)},',
    );
    buffer.writeln(
      '    surfaceContainerLow: ${_colorToConst(scheme.surfaceContainerLow)},',
    );
    buffer.writeln(
      '    surfaceContainer: ${_colorToConst(scheme.surfaceContainer)},',
    );
    buffer.writeln(
      '    surfaceContainerHigh: ${_colorToConst(scheme.surfaceContainerHigh)},',
    );
    buffer.writeln(
      '    surfaceContainerHighest: ${_colorToConst(scheme.surfaceContainerHighest)},',
    );
    buffer.writeln(
      '    onSurfaceVariant: ${_colorToConst(scheme.onSurfaceVariant)},',
    );
    buffer.writeln('    outline: ${_colorToConst(scheme.outline)},');
    buffer.writeln(
      '    outlineVariant: ${_colorToConst(scheme.outlineVariant)},',
    );
    buffer.writeln('    shadow: ${_colorToConst(scheme.shadow)},');
    buffer.writeln('    scrim: ${_colorToConst(scheme.scrim)},');
    buffer.writeln(
      '    inverseSurface: ${_colorToConst(scheme.inverseSurface)},',
    );
    buffer.writeln(
      '    onInverseSurface: ${_colorToConst(scheme.onInverseSurface)},',
    );
    buffer.writeln(
      '    inversePrimary: ${_colorToConst(scheme.inversePrimary)},',
    );
    buffer.writeln('    surfaceTint: ${_colorToConst(scheme.surfaceTint)},');
  }

  static String _colorToConst(Color color) {
    final a = (color.a * 255).round();
    final r = (color.r * 255).round();
    final g = (color.g * 255).round();
    final b = (color.b * 255).round();

    final hex = ((a << 24) | (r << 16) | (g << 8) | b)
        .toRadixString(16)
        .padLeft(8, '0')
        .toUpperCase();
    return 'Color(0x$hex)';
  }
}
